create table
  public.purchases (
    id bigint generated by default as identity,
    transaction_id bigint not null,
    item text not null,
    price double precision not null,
    category text null,
    warranty_date text null,
    return_date text null,
    constraint Purchase_pkey primary key (id),
    constraint purchases_transaction_id_fkey foreign key (transaction_id) references transactions (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.receipts (
    id bigint generated by default as identity,
    transaction_id bigint null,
    image text null,
    constraint Reciept_pkey primary key (id),
    constraint receipts_transaction_id_fkey foreign key (transaction_id) references transactions (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.transactions (
    id bigint generated by default as identity,
    user_id bigint not null,
    merchant text null,
    description text null,
    created_at timestamp with time zone not null default now(),
    constraint Transaction_pkey primary key (id),
    constraint transactions_user_id_fkey foreign key (user_id) references users (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.users (
    id bigint generated by default as identity,
    name text not null,
    email text not null,
    constraint Users_pkey primary key (id)
  ) tablespace pg_default;